image: docker
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

build_image:
  stage: build
  only:
    - merge_requests
  script:
    - docker build .
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - runner_unsupported

fetch_versions:
  stage: test
  dependencies:
    - build_image
  script:
    - docker build -t mycicdimage .
    - docker run mycicdimage "solc --version; node -v; npm -v; truffle version"
