default:

stages:
  - build
  - test

build_image:
  stage: build
  image: docker
  services:
    - docker:dind
  entrypoint: [""]
  only:
    - merge_requests
  script:
    - docker build .
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - runner_unsupported
